version: "3.8"
services:
    client:
        build: ./client
        image: client-reservation:v1
        container_name: client-react-reservation
        ports: 
            - "3000:3000"
        networks: 
            - reservation
        depends_on: 
            - server
        stdin_open: true
    server:
        build: ./server
        image: server-reservation:v1
        container_name: server-node-reservation
        ports: 
            - "8080:8080"
        networks: 
            - reservation
networks: 
    reservation:
        driver: bridge